### ISSUE TITLE
Health Check example does not work with Avro

### ISSUE THREAD

**Issue by serras** [higherkindness/mu-scala-examples#3]
When trying to execute the `health-check` from `examples` but using Avro as serialization format instead of Protocol Buffers, everything compiled fine but it didn't work at run-time with error such as:

```
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@5b7b256
java.lang.ClassCastException: class org.apache.avro.util.Utf8 cannot be cast to class org.apache.avro.generic.GenericRecord (org.apache.avro.util.Utf8 and org.apache.avro.generic.GenericRecord are in unnamed module of loader sbt.internal.LayeredClassLoader @1938006a)
```

After some discussion with @cb372 it turned out that `modules/health-check-unary/src/main/scala/higherkindness/mu/rpc/healthcheck/unary/handler/ServerStatus.scala` included the following line:

```scala
class HealthCheck(val nameService: String) extends AnyVal
```

once I changed it to read

```scala
case class HealthCheck(val nameService: String)
```

the problems went away.

Our discussion continued and @cb372 added the following comment:

> Because of this, it doesn’t support automatic derivation for normal classes, only for case classes. I suspect the extends `AnyVal` was a bit of a red herring, and turning the class into a case class is what fixed things.

I am not sure what should be the right way to go regarding this. My expectation was that if some class cannot be serialized I would get an error at compile-time, not at run-time.

**Comment by cb372** [comment]
>My expectation was that if some class cannot be serialized I would get an error at compile-time, not at run-time.

I agree with this. We could check in the `@service` macro that all request/response types are case classes, but currently we don't.

See https://github.com/47deg/marlow/issues/513#issuecomment-604500713 for more discussion on this point.

Anyway, I'll do the one-line fix to make the healthcheck work.

**Comment by dmarticus** [comment]
Is this issue still relevant @serras @cb372?  I don't see the `unary` health in these examples any more, just the `fs2` and the `monix` health checks.  Is there something I'm missing?

**Comment by serras** [comment]
I guess you can close it. @cb372's integration tests ensure that both languages talk the same protocol.
