### ISSUE TITLE
Rewrite the todolist example to remove the frees dependency

### ISSUE THREAD

**Issue by cb372** [higherkindness/mu-scala-examples#4]
This is currently blocking us from upgrading the examples to Scala 2.13.

I had a look at it but it's non-trivial so I'll just make an issue for now. I was hoping we could just copy the necessary `.scala` files from the `frees` repo, but they have freestyle `@tagless` and `@module` macro annotations.

**Comment by rafaparadela** [comment]
Assigned to @dmarticus
