### ISSUE TITLE
Update all examples to use sbt-mu-srcgen

### ISSUE THREAD

**Issue by cb372** [higherkindness/mu-scala-examples#8]
This is what we recommend for real apps, so we should demonstrate it in the examples.

Currently most of the examples use hand-written Scala code for their protocols. Some also have IDL files in their `resources` directory but they are not used for anything.

**Comment by dmarticus** [comment]
I'm going to tackle this once all the changes for https://github.com/higherkindness/sbt-mu-srcgen/issues/38 are out; since it'll affect how I use the sbt-mu-srcgen plugin.
